# nixpacks.toml

[variables]
PIP_NO_CACHE_DIR = "1"
PYTHONUNBUFFERED = "1"
ULTRALYTICS_AGREE = "True"

[phases.setup]
commands = [
  "python -m pip install --upgrade pip setuptools wheel"
]

[phases.install]
commands = [
  # Ensure no GUI OpenCV remains in the layer cache
  "python -m pip uninstall -y opencv-python opencv-contrib-python cv2 || true",

  # Fresh install of your requirements (the ones you pasted)
  "python -m pip install --no-cache-dir -r requirements.txt",

  # Quick visibility: which opencv packages are present?
  "python - <<'PY'\nimport pkgutil\nmods=[m.name for m in pkgutil.iter_modules()]\nprint('has opencv_python? ', any('opencv_python' in m for m in mods))\nprint('has opencv_contrib_python? ', any('opencv_contrib_python' in m for m in mods))\nPY",

  # HARD FAIL if not headless (prevents deploying a broken image)
  "python - <<'PY'\nimport cv2, sys\nbi=cv2.getBuildInformation().lower()\nprint('cv2 version:', cv2.__version__)\nprint('headless?', 'headless' in bi)\nassert 'headless' in bi, 'ERROR: Non-headless OpenCV wheel detected'\nPY"
]
